# Generated by Django 3.2.5 on 2021-07-27 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210727_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('time', models.TimeField(choices=[(datetime.time(9, 0), '9:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(15, 0), '3:00 PM'), (datetime.time(18, 0), '6:00 PM'), (datetime.time(21, 0), '9:00 PM')])),
                ('rate', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('theatre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.theatre')),
            ],
        ),
    ]
